package messaging

import (
	"context"
	"errors"
	"time"
)

type UserID int

type MessageKind string

var ErrMessageNotFound = errors.New("message not found")

const (
	KindDirectMessage    MessageKind = "direct_message"
	KindMessageAck       MessageKind = "message_ack"
	KindMessageDelivered MessageKind = "message_delivered"
	KindMessageRead      MessageKind = "message_read"
	KindPresenceState    MessageKind = "presence_state"
	KindUserOnline       MessageKind = "user_online"
	KindUserOffline      MessageKind = "user_offline"
	KindError            MessageKind = "error"
)

// Message is the normalized real-time payload envelope for the messaging domain.
type Message struct {
	ID                int64       `json:"id,omitempty"`
	Type              MessageKind `json:"type"`
	From              string      `json:"from,omitempty"`
	To                string      `json:"to,omitempty"`
	Body              string      `json:"body,omitempty"`
	ContentKind       string      `json:"content_kind,omitempty"`
	Ciphertext        string      `json:"ciphertext,omitempty"`
	EnvelopeVersion   string      `json:"envelope_version,omitempty"`
	SenderDeviceID    int64       `json:"sender_device_id,omitempty"`
	RecipientDeviceID int64       `json:"recipient_device_id,omitempty"`
	Users             []string    `json:"users,omitempty"`
	StoredMessageID   int64       `json:"stored_message_id,omitempty"`
}

// Thread models a future conversation primitive (DM thread, group thread, marketplace order thread).
type Thread struct {
	ID      string
	Members []UserID
}

// DeliveryReceipt captures adapter-level delivery outcomes.
type DeliveryReceipt struct {
	MessageID       int64
	StoredMessageID int64
	Delivered       bool
	Reason          string
}

// ClientMessageCorrelation records the mapping between a client-provided real-time
// message ID and the durable stored message ID generated by the server.
type ClientMessageCorrelation struct {
	SenderUserID    int
	RecipientUserID int
	ClientMessageID int64
	StoredMessageID int64
	Delivered       bool
}

// StoredMessage is the durable message record shape used for persistence and sync.
type StoredMessage struct {
	ID                int64
	FromUserID        int
	ToUserID          int
	Body              string
	ContentKind       string
	Ciphertext        string
	EnvelopeVersion   string
	SenderDeviceID    int64
	RecipientDeviceID int64
	CreatedAt         time.Time
	DeliveredAt       *time.Time
	ReadAt            *time.Time
	ClientMessageID   int64
	DeliveryFailed    bool
}

// Transport is the adapter seam for centralized relay today and P2P transports later.
type Transport interface {
	SendDirect(toUserID int, msg Message) bool
}

// ClientMessageCorrelationRecorder persists client-ID to durable-ID mappings for
// reconciliation/debugging without changing the WS protocol.
type ClientMessageCorrelationRecorder interface {
	RecordClientMessageCorrelation(ctx context.Context, c ClientMessageCorrelation) error
}

// SessionAuthenticator validates a real-time session token.
type SessionAuthenticator interface {
	AuthenticateSession(ctx context.Context, token string) (userID int, username string, err error)
}

// UserResolver resolves an addressable recipient identifier to an internal user ID.
type UserResolver interface {
	ResolveUserID(ctx context.Context, username string) (int, error)
}

// KeyMaterialProvider is reserved for future E2EE/P2P key lookup.
type KeyMaterialProvider interface {
	MessagingPublicKey(ctx context.Context, userID int, purpose string) ([]byte, error)
}
